CREATE TABLE Restaurant (
  id SERIAL PRIMARY KEY,
  Restaurant_Name VARCHAR(255) NOT NULL,
  Rating VARCHAR(5) NOT NULL,
  Category VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL,
  Latitude VARCHAR(255) NOT NULL,
  Longitude VARCHAR(255) NOT NULL,
  Province VARCHAR(255) NOT NULL
);